#
#   Date - 16.05.2022
#
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
#
#
#
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"
#
#
#
# Constraints:
#
#     0 <= s.length <= 1000
#     t.length == s.length + 1
#     s and t consist of lowercase English letters.
#


from math import prod
import timeit
from typing import List, Optional, Set


def findTheDifference(s: str, t: str) -> str:
    """
    The best way to get ahead is to get starting..?
    """
    # # Algorithmic Solution
    # using ascii value 

    # # Pythonic Solution
    # ss = list(s)
    # tt = list(t)
    # while True:
    #     lt = tt.pop()
    #     try:
    #         ss.pop(ss.index(lt))
    #     except ValueError:
    #         return lt


def testing():
    result = findTheDifference(s="abcd", t="abcde")
    # print(f"result: {result}")
    assert ("e" == result)

    result = findTheDifference(s="", t="y")
    # print(f"result: {result}")
    assert ("y" == result)

    # result = findTheDifference(s=124356)
    # # print(f"result: {result}")
    # assert (124356 == result)


if __name__ == '__main__':
    print("\n Finished in --- %.5f seconds ---" %
          (timeit.timeit(testing, number=100)))
